# Generated by Django 4.0.6 on 2022-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipodocumento', models.CharField(max_length=25)),
                ('Documento', models.PositiveIntegerField()),
                ('Nombres', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(max_length=25)),
                ('Hobbie', models.CharField(max_length=25)),
            ],
        ),
    ]
