# Generated by Django 4.0.6 on 2022-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_persona_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
    ]
