# Generated by Django 4.0.6 on 2022-07-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Documento',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Apellidos',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Nombres',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Tipodocumento',
            new_name='type_document',
        ),
    ]
