# Generated by Django 4.0.6 on 2022-07-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_documento_persona_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Hobbie',
            new_name='hobbie',
        ),
    ]
